version: '3.8'

services:
  # 服务端
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
    command: ["python", "main.py", "dev"]

  # 前端（如果需要）
  frontend:
    image: node:16
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]

  # 本地模型服务
  local_model:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ENV=dev
    command: ["python", "main.py", "dev", "local_model"]

  # 异步服务（Celery）
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=dev
    command: ["python", "main.py", "dev", "celery"]